### ISSUE TITLE
Discussion board

### ISSUE THREAD

**Issue by fillemazendacus** [rbbrdckybk/dream-factory#12]
I feel like I'm getting a bit out of the program-specific realm now, which is why I'm first wondering if there's some sort of discussion board for Dream Factor users? Just to share experiences, for example in terms of formatting prompts.
I'm stuck with a problem where the higher the resolution, the more duplicates there will be for example portrait. I've tried different samplers, now also upscale (which doesn't give satisfactory quality, like any AI increase), different scale and steps values - all without results. Does anyone have any good advice on wording a prompt? Maybe someone has found a suitable negative prompt wording to avoid multiplications? I'd be interested in getting a 1088px with ONE object, like in 512px, not the bigger the image, the more versions of the same object.
![Einsxmple](https://user-images.githubusercontent.com/79479381/197003294-35488700-7e74-4c11-a924-d0477c4fd475.jpg)

**Comment by rbbrdckybk** [comment]
The [Stable Diffusion subreddit](https://www.reddit.com/r/StableDiffusion/) is a decent resource for usage tips.

Since SD was trained on 512x512 images, it doesn't do well doing native generations above that size. 1088x1088 is more than quadruple the resolution, so it's essentially tiling four 512x512 images into your output, resulting in 4 Einsteins.

My understanding of best practice to generate high-quality output above 512x512:

1) Generate initial images at 512x512.
2) Upscale to your desired resolution (or the highest resolution that SD can generate on your GPU).
3) Feed the upscaled output back into SD as an input image and re-use the same prompt from step 1 to help "guide" SD into producing a coherent high-res image.

**Comment by fillemazendacus** [comment]
Thank you so much! :)
Using input image is one option I have tried too, but there are some difficulties to get all the parameters right. But definitely I'm going to dig into suggested SD subreddit too.
Thank you again - your Dream Factory is very useful tool! :)
