### ISSUE TITLE
Installation taking over 30 minutes (+ Conda taking time), can this please be improved?

### ISSUE THREAD

**Issue by Testertime** [rbbrdckybk/dream-factory#24]
Sorry I'm sure this is strange to ask, but it would be amazing to run this on Kaggle. However file persistence does not work too well there, so it has to be reinstalled every time. Is there anything I / you can do to improve installation times? Installing PyTorch **and** all other components with Automatic1111 only take like 1/6 of the time.

Thank you!

**Comment by Canditi890** [comment]
I had a similar problem, I solved it by installing manually through python without anaconda

**Comment by rbbrdckybk** [comment]
Like Canditi890 mentioned, since you're installing on a non-persistent environment, there's no need for Anaconda. Take a look at setup.py, specifically these functions:
```
install_pytorch
install_dependencies
```
You should be able to create a simple script to install these thing manually without Anaconda, and the process should be much faster. If you install Auto1111 first and run DF in the same environment, you can even skip the Pytorch install; DF should run fine with the version that Auto1111 installs.
